# ===========================================================================
# Project:   ExceptionsClient
# Copyright: ©2010 Antonio Garrote.
# ===========================================================================

# Add initial buildfile information here
config :all, :required => :sproutcore
