require 'rake/clean'

INCLUDE = "include"

ERLC_FLAGS = "-I#{INCLUDE} +warn_unused_vars +warn_unused_import"
ERLC_INCLUDES = "-pa ebin -pa deps/rabbitmq-server/ebin -pa deps/rabbitmq-erlang-client/ebin -pa deps/mochiweb/ebin"

SRC = FileList['*.erl']
OBJ = SRC.pathmap("%{src,ebin}X.beam")

CLEAN.include("ebin/*.beam")

directory 'ebin'

rule ".beam" => ["%{ebin,src}X.erl"] do |t|
  sh "erlc -D EUNIT #{ERLC_INCLUDES} -pa deps-W #{ERLC_FLAGS} -o ebin #{t.source}"
end

task :compile => ['ebin'] + OBJ

task :default => :compile
